//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplashImageViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplashImageViewer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        public static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple image viewer with slideshow feature..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte(s).
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing UI language requires app restart..
        /// </summary>
        public static string ChangingUILanguageRequiresAppRestart {
            get {
                return ResourceManager.GetString("ChangingUILanguageRequiresAppRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to check for available updates.
        /// </summary>
        public static string CheckForAvailableUpdates {
            get {
                return ResourceManager.GetString("CheckForAvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for available updates.
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum screen resolution requirements not met.
        /// </summary>
        public static string CheckScreenDimensionsWarning {
            get {
                return ResourceManager.GetString("CheckScreenDimensionsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for available updates.
        /// </summary>
        public static string CheckUpdatesButtonToolTip {
            get {
                return ResourceManager.GetString("CheckUpdatesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close Image.
        /// </summary>
        public static string CloseImageMenuItem {
            get {
                return ResourceManager.GetString("CloseImageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings.
        /// </summary>
        public static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a file currently open [DEL].
        /// </summary>
        public static string DeleteButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File delete confirmation required.
        /// </summary>
        public static string FileDeleteConfirmationRequired {
            get {
                return ResourceManager.GetString("FileDeleteConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        public static string FileDeletePrompt {
            get {
                return ResourceManager.GetString("FileDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string FileToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force check updates.
        /// </summary>
        public static string ForceCheckUpdates {
            get {
                return ResourceManager.GetString("ForceCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force program update?.
        /// </summary>
        public static string ForceProgramUpdatePrompt {
            get {
                return ResourceManager.GetString("ForceProgramUpdatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press, to force program update.
        /// </summary>
        public static string ForceProgramUpdateToolTip {
            get {
                return ResourceManager.GetString("ForceProgramUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen mode [F].
        /// </summary>
        public static string FullscreenButtonToolTip {
            get {
                return ResourceManager.GetString("FullscreenButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered.
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string GeneralWarning {
            get {
                return ResourceManager.GetString("GeneralWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID was not found.
        /// </summary>
        public static string GuidWasNotFound {
            get {
                return ResourceManager.GetString("GuidWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded package hash sum mismatch.
        /// </summary>
        public static string HashSumMismatch {
            get {
                return ResourceManager.GetString("HashSumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image modified.
        /// </summary>
        public static string ImageModified {
            get {
                return ResourceManager.GetString("ImageModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE MODIFIED.
        /// </summary>
        public static string ImageModifiedCaps {
            get {
                return ResourceManager.GetString("ImageModifiedCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kbyte.
        /// </summary>
        public static string KByte {
            get {
                return ResourceManager.GetString("KByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last check.
        /// </summary>
        public static string LastCheck {
            get {
                return ResourceManager.GetString("LastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyte.
        /// </summary>
        public static string MByte {
            get {
                return ResourceManager.GetString("MByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocated.
        /// </summary>
        public static string MemoryAllocated {
            get {
                return ResourceManager.GetString("MemoryAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method needs to be called first.
        /// </summary>
        public static string MethodNeedsToBeCalledFirst {
            get {
                return ResourceManager.GetString("MethodNeedsToBeCalledFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified file overwrite confirmation required.
        /// </summary>
        public static string ModifiedFileOverwriteConfirmationRequired {
            get {
                return ResourceManager.GetString("ModifiedFileOverwriteConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer program version available.
        /// </summary>
        public static string NewerProgramVersionAvailable {
            get {
                return ResourceManager.GetString("NewerProgramVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image [RIGHT/UP ARROW].
        /// </summary>
        public static string NextButtonToolTip {
            get {
                return ResourceManager.GetString("NextButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Folder.
        /// </summary>
        public static string OpenFolderMenuItem {
            get {
                return ResourceManager.GetString("OpenFolderMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Image.
        /// </summary>
        public static string OpenImageMenuItem {
            get {
                return ResourceManager.GetString("OpenImageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings [S].
        /// </summary>
        public static string OpenSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("OpenSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite current image?.
        /// </summary>
        public static string OverwriteImagePrompt {
            get {
                return ResourceManager.GetString("OverwriteImagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image [LEFT/DOWN ARROW].
        /// </summary>
        public static string PreviousButtonToolTip {
            get {
                return ResourceManager.GetString("PreviousButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current program version is up to date.
        /// </summary>
        public static string ProgramIsUpToDate {
            get {
                return ResourceManager.GetString("ProgramIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program update.
        /// </summary>
        public static string ProgramUpdate {
            get {
                return ResourceManager.GetString("ProgramUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select random image [R].
        /// </summary>
        public static string RandomButtonToolTip {
            get {
                return ResourceManager.GetString("RandomButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize slideshow order.
        /// </summary>
        public static string RandomizeSlideshowOrder {
            get {
                return ResourceManager.GetString("RandomizeSlideshowOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recent Items.
        /// </summary>
        public static string RecentItemsMenuItem {
            get {
                return ResourceManager.GetString("RecentItemsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        public static string ResetSettingsPrompt {
            get {
                return ResourceManager.GetString("ResetSettingsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate image [D].
        /// </summary>
        public static string RotateImageButtonToolTip {
            get {
                return ResourceManager.GetString("RotateImageButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images in subdirectories.
        /// </summary>
        public static string SearchImagesInSubdirectories {
            get {
                return ResourceManager.GetString("SearchImagesInSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds remaining.
        /// </summary>
        public static string SecondsRemaining {
            get {
                return ResourceManager.GetString("SecondsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit changes.
        /// </summary>
        public static string SettingsCommitToolTip {
            get {
                return ResourceManager.GetString("SettingsCommitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        public static string SettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SettingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/stop slideshow [SPACE].
        /// </summary>
        public static string SlideshowButtonToolTip {
            get {
                return ResourceManager.GetString("SlideshowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDESHOW ENABLED.
        /// </summary>
        public static string SlideshowEnabled {
            get {
                return ResourceManager.GetString("SlideshowEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [F] or [ESC] to exit fullscreen mode.
        /// </summary>
        public static string SlideshowInfoLabel {
            get {
                return ResourceManager.GetString("SlideshowInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow mode is active.
        /// </summary>
        public static string SlideshowModeIsActive {
            get {
                return ResourceManager.GetString("SlideshowModeIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow transition (s):.
        /// </summary>
        public static string SlideshowTransition {
            get {
                return ResourceManager.GetString("SlideshowTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit project source code repository on github.com.
        /// </summary>
        public static string SourceCodeRepoToolTip {
            get {
                return ResourceManager.GetString("SourceCodeRepoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop slideshow first..
        /// </summary>
        public static string StopSlideshowFirstPrompt {
            get {
                return ResourceManager.GetString("StopSlideshowFirstPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme color:.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI language:.
        /// </summary>
        public static string UILanguage {
            get {
                return ResourceManager.GetString("UILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI language changed.
        /// </summary>
        public static string UILanguageChanged {
            get {
                return ResourceManager.GetString("UILanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in progress.
        /// </summary>
        public static string UpdateInProgress {
            get {
                return ResourceManager.GetString("UpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update program?.
        /// </summary>
        public static string UpdateProgramPrompt {
            get {
                return ResourceManager.GetString("UpdateProgramPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in/out image [Z].
        /// </summary>
        public static string ZoomButtonToolTip {
            get {
                return ResourceManager.GetString("ZoomButtonToolTip", resourceCulture);
            }
        }
    }
}
